## **Indexing, Slicing and Reshaping**

In [2]:
import numpy as np

In [ ]:
#Indexing

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


In [6]:
print(arr[-1])

50


In [9]:
# 2d array indexing
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr2D[1, 2])      # index starts with 0, row index 1 and column index 2

6


In [16]:
print(arr2D[2, -1])

9


In [12]:
print(arr2D[1, :])

[4 5 6]


In [13]:
print(arr)

[10 20 30 40 50]


In [14]:
print(arr[1:4])

[20 30 40]


In [18]:
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Slicing - rows 0 and 1, columns 0 and 1, -> 2 is exclusive

sliced_array = arr2D[0:2, 0:2]
print(sliced_array)

[[1 2]
 [4 5]]


In [19]:
sliced_array2 = arr2D[0:2, 1:3]
print(sliced_array2)

[[2 3]
 [5 6]]


In [ ]:
sliced_array3 = arr2D[1, :]         # takes 1 index row and prints all the elements from index 1 row
print(sliced_array3)

[4 5 6]


In [27]:
# Boolean indexing

arr2 = np.array([1, 2, 3, 4, 5])
mask = arr2 < 3

arr2[mask]

array([1, 2])

In [31]:
# Fancy indexing

arr = np.array([10, 20, 30, 40, 50])
indexes = [0, 2, 4]

print(arr[indexes])

[10 30 50]


In [36]:


a = np.array([1, 2, 3, 4, 5])
a = a + 1
print(a)

[2 3 4 5 6]


In [37]:
# Reshaping

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [39]:
arr = arr.reshape(3, 4)
print(arr)

arr = arr.reshape(4, 3)
print(arr)

arr = arr.reshape(6, 2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [40]:
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [41]:
# Faltten

arr = arr.flatten()
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
arr3 = np.array([1, 2, 3])
arr3_2d = arr3[np.newaxis,1]
print(arr3_2d)

[2]
