# **Numpy - Activity File 1**

In [1]:
import numpy as np

## **ndarray**

In [2]:
arr1 = np.array([1, 2, 3])

print(arr1)

[1 2 3]


In [4]:
type(arr1)          # Since we created this array using np, its a numpy.ndarray

numpy.ndarray

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr3 = np.array((1, 2, 3, 4, 5))                # Since its np.array, though its tuple, it will print an array. 

print(arr3)

[1 2 3 4 5]


### **ndarray with attributes**

In [8]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
# shape 
# one dimension - (row)
# two dimension - (row, column)
# three dimension - (row, column, width)

arr4.shape

(3, 5)

In [25]:
# number of dimensions
arr4.ndim

2

In [26]:
# Size - total elements
arr4.size

15

In [27]:
# data type
arr4.dtype

dtype('int64')

In [28]:
# Example

my_arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]], [[13, 14], [15, 16], [17, 18]]])

print(my_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [29]:
my_arr.shape

(3, 3, 2)

In [30]:
my_arr.ndim

3

In [31]:
my_arr.size

18

In [33]:
my_arr.dtype

dtype('int64')

## **Special Arrays**

In [ ]:
# Zeros
arr0 = np.zeros((3, 5))     # an array with 3x5 shape and all values as 0

print(arr0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
arr0.dtype

dtype('float64')

In [38]:
arr0 = np.zeros((3, 5), dtype='int')           # changing the data type of the elements from float to int

print(arr0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [39]:
arr0.dtype

dtype('int64')

In [41]:
# Ones

arr1s = np.ones((2, 8), dtype='float')          # An arrya with 2x8 shape and all the values are 1.0

print(arr1s)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [42]:
# full

arrfull = np.full((4, 4), 7)                    # An array with 4x4 shape and all values as 7

print(arrfull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [44]:
# Identity matrix - diagonal elements are 1s and remaining all are 0

arrId = np.eye(4, dtype='int')
print(arrId)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
