# **Numpy - Activity File 1**

In [52]:
import numpy as np

## **ndarray**

In [53]:
arr1 = np.array([1, 2, 3])

print(arr1)

[1 2 3]


In [54]:
type(arr1)          # Since we created this array using np, its a numpy.ndarray

numpy.ndarray

In [55]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [56]:
arr3 = np.array((1, 2, 3, 4, 5))                # Since its np.array, though its tuple, it will print an array. 

print(arr3)

[1 2 3 4 5]


### **ndarray with attributes**

In [57]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [58]:
# shape 
# one dimension - (row)
# two dimension - (row, column)
# three dimension - (row, column, width)

arr4.shape

(3, 5)

In [59]:
# number of dimensions
arr4.ndim

2

In [60]:
# Size - total elements
arr4.size

15

In [61]:
# data type
arr4.dtype

dtype('int64')

In [62]:
# Example

my_arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]], [[13, 14], [15, 16], [17, 18]]])

print(my_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [63]:
my_arr.shape

(3, 3, 2)

In [64]:
my_arr.ndim

3

In [65]:
my_arr.size

18

In [66]:
my_arr.dtype

dtype('int64')

## **Special Arrays**

In [67]:
# Zeros
arr0 = np.zeros((3, 5))     # an array with 3x5 shape and all values as 0

print(arr0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [68]:
arr0.dtype

dtype('float64')

In [69]:
arr0 = np.zeros((3, 5), dtype='int')           # changing the data type of the elements from float to int

print(arr0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [70]:
arr0.dtype

dtype('int64')

In [71]:
# Ones

arr1s = np.ones((2, 8), dtype='float')          # An arrya with 2x8 shape and all the values are 1.0

print(arr1s)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [72]:
# full

arrfull = np.full((4, 4), 7)                    # An array with 4x4 shape and all values as 7

print(arrfull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [73]:
# Identity matrix - diagonal elements are 1s and remaining all are 0

arrId = np.eye(4, dtype='int')
print(arrId)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [74]:
# array sequence

arrSeq = np.arange(5)

print(arrSeq)

[0 1 2 3 4]


In [75]:
arrSeq2 = np.arange(2, 10, 2)
print(arrSeq2)

[2 4 6 8]


In [ ]:
# Equally spaced values
# np.set_printoptions(precision=3)  # Set display precision to 3 decimal places
equally_spaced_values = np.linspace(1, 3, 20)

print(equally_spaced_values)

[1.    1.105 1.211 1.316 1.421 1.526 1.632 1.737 1.842 1.947 2.053 2.158
 2.263 2.368 2.474 2.579 2.684 2.789 2.895 3.   ]


In [77]:
eq_sp_vl = np.linspace(5, 10, 10)

print(eq_sp_vl)

[ 5.     5.556  6.111  6.667  7.222  7.778  8.333  8.889  9.444 10.   ]


In [ ]:
# random distribution

arr_rand = np.random.rand(3,4)  # 3x4 array with random values between 0(inclusive) and 1(exclusive) [0, 1)

print(arr_rand)

[[0.229 0.719 0.961 0.741]
 [0.466 0.769 0.268 0.246]
 [0.699 0.099 0.596 0.115]]


In [88]:
#

arr2_rand = np.random.rand(2, 3)

print(arr2_rand)

[[0.846 0.338 0.901]
 [0.601 0.441 0.584]]


In [83]:
#

arr_randint = np.random.randint(5, 10, size=(3, 7))
print(arr_randint)

[[5 5 7 6 8 8 7]
 [8 8 6 6 7 8 8]
 [8 6 6 9 5 7 7]]


In [86]:
arr_randint2 = np.random.randint(5, 10, size=(3, 7))
print(arr_randint2)

[[5 8 5 7 9 9 7]
 [9 6 8 5 8 9 5]
 [7 5 6 6 5 7 7]]


In [94]:
arr_randint3 = np.random.randint(5, 10, size=(4, 20))   # 3x7 array with random integers between 5 and 10 [5, 10)
print(arr_randint3)

[[9 6 7 9 7 7 5 5 7 7 7 5 8 8 9 5 6 6 7 8]
 [9 6 7 9 5 5 6 9 5 5 8 7 8 7 6 6 9 5 8 8]
 [8 5 7 7 7 8 9 6 6 7 7 9 6 7 9 7 9 5 6 7]
 [5 8 9 9 9 6 8 9 5 6 9 8 7 9 6 5 9 7 8 6]]


In [90]:
arrA = np.array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 8.9])
arrA = arrA.astype('int')
print(arrA)

[1 2 3 4 5 6 7 8]
