## **Array Operations and Broadcasting**

In [2]:
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

In [4]:
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
# Broadcasting - adding scalar to array

a1 + 10

array([11, 12, 13])

In [10]:

arr2 = np.array([1, 4, 9, 16])

print(np.sqrt(arr2))        # Square root of each element
print(np.log(arr2))        # Natural logarithm of each element
print(np.exp(arr2))        # Exponential of each element
print(np.sin(arr2))        # Sine of each element (in radians)
print(np.cos(arr2))        # Cosine of each element (in radians)

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [ ]:
arr4 = np.array([])