## **NumPy Cheatsheet — Part 4: Advanced Indexing, Sorting & Stacking**



### **1. Conditional Selection (`where`)**

Syntax: 
    np.where(condition, value_if_true, value_if_false)

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 25, 1, 0)
print(result)

[0 0 1 1 1]


### **2. Extracting Non-zero Elements**

In [6]:
arr = np.array([10, 0, 42, 0, 3, 0, 0, 56])
indices = np.nonzero(arr)                               # non zero indices
print(indices)

print(arr[indices])                         # print non zero elements

(array([0, 2, 4, 7]),)
[10 42  3 56]


### **3. Sorting Arrays**

In [ ]:
arr = np.array([1, 5, 3, 5, 4, 8, 6])
print(np.sort(arr))

[1 3 4 5 5 6 8]


In [12]:
arr2d = np.array([[3, 1, 2], [10, 5, 9]])
print(np.sort(arr2d))

print(np.sort(arr2d, axis=1))

[[ 1  2  3]
 [ 5  9 10]]
[[ 1  2  3]
 [ 5  9 10]]


**Argsort (indices of sorted order):**

In [17]:
print(arr)
print(np.sort(arr))
print(np.argsort(arr))


print(arr2d)
print(np.sort(arr2d))
print(np.argsort(arr2d))




[1 5 3 5 4 8 6]
[1 3 4 5 5 6 8]
[0 2 4 1 3 6 5]
[[ 3  1  2]
 [10  5  9]]
[[ 1  2  3]
 [ 5  9 10]]
[[1 2 0]
 [1 2 0]]
