## **NumPy Cheatsheet — Part 2: Indexing, Slicing & Reshaping**

### **1. Indexing (Accessing Elements)**

**1D Array:**

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])


10
50


**2D Array:**

In [6]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

print(arr2d[0, 1])
print(arr2d[2, -1])

2
9


### **2. Slicing (Extracting Ranges)**

**1D Array:**

In [9]:
print(arr)
print(arr[1:4])
print(arr[:3])
print(arr[::2])

[10 20 30 40 50]
[20 30 40]
[10 20 30]
[10 30 50]


**2D Array:**

In [12]:
print(arr2d)
print(arr2d[0:2, 1:3]) # Rows 0-1, cols 1-2
print(arr2d[:, 0])  # First column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4 7]


### **3. Boolean Indexing**

In [15]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr < 3
print(mask)
print(arr[mask])

[ True  True False False False]
[1 2]


### **4. Fancy Indexing (Index by List/Array)**

In [17]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 4, 3]
print(arr[indices])

[10 50 40]


**2D Example:**

In [18]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr2d[[0, 2], [2, 1]]

array([3, 8])

### **5. Reshaping Arrays**

In [25]:
arr = np.arange(1, 9)
print(arr)
reshaped = arr.reshape((2, 4))
print(reshaped)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


### **6. Flattening Arrays**


In [28]:
flat_arr = reshaped.flatten()
print(flat_arr)

reshaped.ravel()

[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

### **7. Adding/Removing Dimensions**

In [33]:
arr = np.array([1, 2, 3])
arr_2d = arr[np.newaxis, :]
print(arr_2d)
arr_2d_col = arr[:, np.newaxis]
print(arr_2d_col)

[[1 2 3]]
[[1]
 [2]
 [3]]
