## **NumPy Cheatsheet — Part 3: Array Operations & Broadcasting**

---

### **1. Element-wise Arithmetic**

**Between arrays:**

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


**With scalars:**

In [8]:
print(a + 10)
print(a * 2)

[11 12 13]
[2 4 6]


### **2. Universal Functions (ufuncs)**

NumPy has **vectorized math functions** that apply element-wise:

In [13]:
arr = np.array([1, 4, 9, 16])
np.sqrt(arr)
np.exp(arr)
np.log(arr)
np.sin(arr)
np.cos(arr)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948])

### **3. Aggregation Functions**

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.std())

21
[5 7 9]
[ 6 15]
3.5
1
6
1.707825127659933


### **4. Broadcasting (Different Shapes)**

Broadcasting lets Numpy do arithematic between arrays of different shapes. 

In [23]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

add_vector = np.array([10, 20, 30])

print(arr + add_vector)

[[11 22 33]
 [14 25 36]]


Even scalar + array works because scalars are treated as having shape `(1,)`

### **5. Comparison Operators**

In [24]:
arr = np.array([1, 2, 3, 4])
print(arr > 2)
print(arr == 3)

[False False  True  True]
[False False  True False]


**Any & All:**

In [25]:
print(np.any(arr > 3))
print(np.all(arr > 0))

True
True


### **6. Clipping Values**

In [ ]:
arr. np.array([1, 5, 8, 10])
np.clip(arr, 3, 8)