## **NumPy Cheatsheet — Part 1: Basics & Array Creation**

### **1. Importing NumPy**

In [2]:
import numpy as np

### **2. Creating Arrays**

**From Python lists/tuples:**

In [8]:
arr1 = np.array([1, 2, 3])              # 1D array
arr2 = np.array([[1, 2], [3, 4]])       # 2D array
arr3 = np.array([[[1, 2], [2, 3]], [[3, 4], [4, 5]], [[5, 6], [6, 7]]]) # 3D array
arr4 = np.array((1, 2, 3, 4))           # From tuple

print('arr1 - 1D array: ', '\n', arr1)
print('arr2 - 2D array: ','\n', arr2)
print('arr3 - 3D array: ','\n', arr3)
print('arr4 - tuple array: ','\n', arr4)

arr1 - 1D array:  
 [1 2 3]
arr2 - 2D array:  
 [[1 2]
 [3 4]]
arr3 - 3D array:  
 [[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]

 [[5 6]
  [6 7]]]
arr4 - tuple array:  
 [1 2 3 4]


**Check type:**

In [9]:
type(arr1)

numpy.ndarray

### **3. Array Attributes**

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("shape: ", arr.shape)        # shape: (2, 3) -> 2 rows, 3 columns
print("ndim: ", arr.ndim)         # number of dimensions: 2 
print("size: ", arr.size)         # size - number of total elements: 6
print("dtype: ", arr.dtype)        # data type: int64

shape:  (2, 3)
ndim:  2
size:  6
dtype:  int64


In [13]:
print('arr3 - 3D array: ','\n', arr3)

print(arr3.shape)       # (3, 2, 2) -> 3 blocks, 2 rows, 2 columns

arr3 - 3D array:  
 [[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]

 [[5 6]
  [6 7]]]
(3, 2, 2)


### **4. Creating Special Arrays**

**Zeros & Ones:**

In [ ]:
# Zeros array

arr_zeros = np.zeros((2, 3))

print("zeros array(float): ", "\n", arr_zeros)
print("data type of arr_zeros: ", arr_zeros.dtype)

# changing the type of the special array to int

arr_zeros_int = np.zeros((2, 3) , dtype='int')

print("zeros array(int): ", "\n", arr_zeros_int)
print("data type of arr_zeros_int: ", arr_zeros_int.dtype)

zeros array(float):  
 [[0. 0. 0.]
 [0. 0. 0.]]
data type of arr_zeros:  float64
zeros array(int):  
 [[0 0 0]
 [0 0 0]]
data type of arr_zeros_int:  int64


In [25]:
# Ones array

arr_ones = np.ones((2, 3))

print("ones array(float): ", "\n", arr_ones)
print("data type of arr_ones: ", arr_ones.dtype)

# changing the type of the special array to int

arr_ones_int = np.ones((2, 3) , dtype='int')

print("ones array(int): ", "\n", arr_ones_int)
print("data type of arr_ones_int: ", arr_ones_int.dtype)

ones array(float):  
 [[1. 1. 1.]
 [1. 1. 1.]]
data type of arr_ones:  float64
ones array(int):  
 [[1 1 1]
 [1 1 1]]
data type of arr_ones_int:  int64


**Filled with a constant:**

In [32]:
arr_const = np.full((2, 3, 2), 7)

print("const array: ", '\n', arr_const)
print("shape: ", arr_const.shape)

const array:  
 [[[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]]
shape:  (2, 3, 2)


**Identity matrix:**

- An identity matrix is a square matrix with 1s on the main diagonal and 0s everywhere else.

In [40]:
# Identity matrix

arr_identity = np.eye(3)

print("Identity matrix: ", '\n', arr_identity)
print("Data type of an identity matrix: ", arr_identity.dtype)

# Convert the data type to int

arr_identity_int = np.eye(3, dtype='int')
print('integer identity matrix: ', '\n', arr_identity_int)
print("Data type of an identity matrix: ", arr_identity_int.dtype)

Identity matrix:  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Data type of an identity matrix:  float64
integer identity matrix:  
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Data type of an identity matrix:  int64


In [41]:
print(np.eye((2)))

[[1. 0.]
 [0. 1.]]


In [45]:
print(np.ones(2, dtype="int"))

[1 1]


### **5. Creating Number Sequences**

**Using `arange` (like `range` but returns NumPy array):**

Syntax: 
    np.arange([start,] stop[, step,], dtype=None)

- start — first value (defaults to 0)
- stop — end value (exclusive: stop is not included)
- step — increment between values (defaults to 1)
- dtype — optional output dtype (NumPy chooses one if you omit it)

In [48]:
print(np.arange(5))
print(np.arange(0, 10, 2))
print(np.arange(1, 20, 2, dtype='float'))

[0 1 2 3 4]
[0 2 4 6 8]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


**Using `linspace` (equally spaced numbers):**

In [49]:
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


### **6. Random Arrays**

**np.random.rand(a, b)**

- a rows, b cloumns
- Returns a axb array of floats sampled from a uniform distribution on [0.0, 1.0).
- Values are in the interval a (inclusive) to b (exclusive).
- Shape can be given as separate positional integers.

In [56]:
arr_rand = np.random.rand(3, 3)     # Uniform [0, 1)
print(arr_rand)

[[9.66577724e-01 4.13778374e-01 8.50127780e-01]
 [1.38195385e-01 3.66591389e-01 4.14695835e-01]
 [3.76703088e-01 8.68727109e-04 4.41250338e-01]]


**np.random.randn(a, b)**

- a rows, b columns
- Returns a axb array of floats sampled from the standard normal distribution (mean 0, std 1).
- Values can be negative or >1; distribution is Gaussian.



In [62]:
arr_randn = np.random.randn(2, 3)

print(arr_randn)

mean_arr = np.mean(arr_randn)
print("mean: ", mean_arr)

std_arr = np.std(arr_randn)
print("standard deviation: ", std_arr)

[[-0.70399431  0.46727207 -1.09889556]
 [-2.98662037 -1.49495735 -0.77027384]]
mean:  -1.0979115608402035
standard deviation:  1.0357915146058898


**np.random.randint(a, b, (c, d))**

- Returns a cxd array of integers sampled uniformly from the discrete range [a, b) — interval a (inclusive) to b (exclusive).
- Call form: np.random.randint(low, high, size). If you pass only one integer as first arg it becomes the exclusive high and low defaults to 0 (use keywords to avoid confusion).



In [65]:
arr_randint = np.random.randint(1, 10, (3, 3))      # Random ints 1–9
print(arr_randint)

[[4 7 2]
 [3 2 6]
 [8 3 7]]


### **7. Changing Data Type**

In [67]:
arr = np.array([1.2, 3.4, 5.6])
arr_int = arr.astype(int)

print(arr_int)

[1 3 5]
